import type { jsPDF } from 'jspdf'

export const PDF_COLORS = {
  navy: [15, 23, 42] as [number, number, number],
  gold: [180, 140, 50] as [number, number, number],
  slate: [71, 85, 105] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
}

const PAGE_MARGIN = 14
const PAGE_WIDTH = 210
const CONTENT_WIDTH = PAGE_WIDTH - PAGE_MARGIN * 2

export function slugifyFilename(name: string): string {
  return name.replace(/[^\w\s-]/g, '').replace(/\s+/g, '-').slice(0, 48) || 'candidate'
}

export function triggerPdfDownload(doc: jsPDF, filename: string): void {
  doc.save(filename)
}

export function addPageHeader(doc: jsPDF, title: string, subtitle?: string): number {
  doc.setFillColor(...PDF_COLORS.navy)
  doc.rect(0, 0, PAGE_WIDTH, 28, 'F')
  doc.setTextColor(...PDF_COLORS.white)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text(title, PAGE_MARGIN, 12)
  if (subtitle) {
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    doc.text(subtitle, PAGE_MARGIN, 20)
  }
  doc.setTextColor(0, 0, 0)
  return 36
}

export function writeSectionTitle(doc: jsPDF, y: number, text: string): number {
  y = ensureSpace(doc, y, 14)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(...PDF_COLORS.navy)
  doc.text(text, PAGE_MARGIN, y)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(0, 0, 0)
  return y + 8
}

export function writeParagraphs(doc: jsPDF, y: number, paragraphs: string[]): number {
  doc.setFontSize(9)
  doc.setTextColor(...PDF_COLORS.slate)
  for (const p of paragraphs) {
    const lines = doc.splitTextToSize(p, CONTENT_WIDTH) as string[]
    for (const line of lines) {
      y = ensureSpace(doc, y, 6)
      doc.text(line, PAGE_MARGIN, y)
      y += 5
    }
    y += 2
  }
  doc.setTextColor(0, 0, 0)
  return y + 4
}

export function writeBullets(doc: jsPDF, y: number, items: string[]): number {
  doc.setFontSize(9)
  for (const item of items) {
    const lines = doc.splitTextToSize(`• ${item}`, CONTENT_WIDTH - 4) as string[]
    for (const line of lines) {
      y = ensureSpace(doc, y, 6)
      doc.text(line, PAGE_MARGIN + 2, y)
      y += 5
    }
  }
  return y + 4
}

export function ensureSpace(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > 285) {
    doc.addPage()
    return PAGE_MARGIN + 10
  }
  return y
}

export function getContentWidth(): number {
  return CONTENT_WIDTH
}

export function getPageMargin(): number {
  return PAGE_MARGIN
}

export function getPageWidth(): number {
  return PAGE_WIDTH
}

export interface CoverPageOptions {
  title: string
  subtitle: string
  candidateName: string
  pathways: string
  readinessScore: number
  documentId: string
  generatedAt: string
}

export function addCoverPage(doc: jsPDF, opts: CoverPageOptions): void {
  doc.setFillColor(...PDF_COLORS.navy)
  doc.rect(0, 0, PAGE_WIDTH, 297, 'F')

  doc.setDrawColor(...PDF_COLORS.gold)
  doc.setLineWidth(0.8)
  doc.line(PAGE_MARGIN, 40, PAGE_WIDTH - PAGE_MARGIN, 40)

  doc.setTextColor(...PDF_COLORS.gold)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text('CONFIDENTIAL — PROFESSIONAL WORK PRODUCT', PAGE_MARGIN, 52)

  doc.setTextColor(...PDF_COLORS.white)
  doc.setFontSize(22)
  doc.text(opts.title, PAGE_MARGIN, 75)

  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  const subLines = doc.splitTextToSize(opts.subtitle, CONTENT_WIDTH) as string[]
  doc.text(subLines, PAGE_MARGIN, 88)

  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text(opts.candidateName, PAGE_MARGIN, 108)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  let y = 120
  const meta = [
    `Visa pathway(s): ${opts.pathways}`,
    `Petition readiness index: ${opts.readinessScore}%`,
    `Generated: ${new Date(opts.generatedAt).toLocaleString('en-US', { dateStyle: 'long', timeStyle: 'short' })}`,
    'Prepared for professional immigration review',
  ]
  for (const line of meta) {
    doc.text(line, PAGE_MARGIN, y)
    y += 7
  }

  doc.setFontSize(8)
  doc.setTextColor(200, 200, 200)
  const disclaimer =
    'This document is generated by Visa Eligibility AI for consulting and legal review. It does not constitute legal advice or a guarantee of visa approval. All claims require independent verification under applicable USCIS standards.'
  const discLines = doc.splitTextToSize(disclaimer, CONTENT_WIDTH) as string[]
  doc.text(discLines, PAGE_MARGIN, 255)

  doc.addPage()
}

export function addPartDivider(doc: jsPDF, part: string, title: string): number {
  const margin = PAGE_MARGIN
  doc.setFillColor(...PDF_COLORS.navy)
  doc.rect(0, 0, PAGE_WIDTH, 50, 'F')
  doc.setTextColor(...PDF_COLORS.gold)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text(part.toUpperCase(), margin, 22)
  doc.setTextColor(...PDF_COLORS.white)
  doc.setFontSize(16)
  doc.text(title, margin, 36)
  doc.setTextColor(0, 0, 0)
  return 58
}

export function addTableOfContents(doc: jsPDF, entries: { label: string; page: number }[]): number {
  let y = PAGE_MARGIN + 6
  y = writeSectionTitle(doc, y, 'Table of Contents')
  doc.setFontSize(9)
  for (const entry of entries) {
    y = ensureSpace(doc, y, 6)
    doc.setFont('helvetica', 'normal')
    doc.text(entry.label, PAGE_MARGIN, y)
    doc.text(String(entry.page), PAGE_WIDTH - PAGE_MARGIN - 8, y, { align: 'right' })
    y += 6
  }
  doc.addPage()
  return PAGE_MARGIN + 10
}

export function applyDocumentFooters(doc: jsPDF, footerLine: string): void {
  const total = doc.getNumberOfPages()
  for (let i = 1; i <= total; i++) {
    doc.setPage(i)
    if (i === 1) continue
    doc.setFontSize(7)
    doc.setTextColor(...PDF_COLORS.slate)
    doc.setFont('helvetica', 'normal')
    doc.text(footerLine, PAGE_MARGIN, 290)
    doc.text(`Page ${i} of ${total}`, PAGE_WIDTH - PAGE_MARGIN, 290, { align: 'right' })
    doc.setTextColor(0, 0, 0)
  }
}

export function getFinalTableY(doc: jsPDF, fallback: number): number {
  const t = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable
  return t?.finalY != null ? t.finalY + 10 : fallback
}

/** Start a table on a fresh page if little vertical space remains. */
export function tableStartY(doc: jsPDF, y: number): number {
  if (y > 235) {
    doc.addPage()
    return PAGE_MARGIN + 10
  }
  return y
}
