import { Shield } from 'lucide-react'
import BenchmarkReportView from './BenchmarkReportView'
import BenchmarkRoadmapPreviewTable from './BenchmarkRoadmapPreviewTable'
import QuantifiedRoadmapTable from './QuantifiedRoadmapTable'
import type { AttorneyDossierData } from '../../lib/export/build-dossier-data'
import type { AssessmentState } from '../../types/assessment'
import { appConfig } from '../../config/app.config'

interface CombinedDossierPreviewProps {
  data: AttorneyDossierData
  state: AssessmentState
}

export default function CombinedDossierPreview({ data, state }: CombinedDossierPreviewProps) {
  const { report } = data

  return (
    <article className="combined-dossier-preview border border-slate-300 bg-white shadow-inner text-slate-800">
      <div className="bg-navy-900 text-white px-8 py-10 border-b-4 border-gold-500">
        <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-gold-400">
          Confidential — Professional work product
        </p>
        <h2 className="mt-3 font-display text-2xl sm:text-3xl tracking-tight">
          EB-1 Professional Review Dossier
        </h2>
        <p className="mt-2 text-sm text-white/80 max-w-2xl">
          Combined benchmark report &amp; profile improvement roadmap · U.S. consulting standard format
        </p>
        <dl className="mt-6 grid sm:grid-cols-2 lg:grid-cols-4 gap-4 text-sm">
          <div>
            <dt className="text-white/50 text-xs uppercase">Candidate</dt>
            <dd className="font-semibold mt-0.5">{data.candidateName}</dd>
          </div>
          <div>
            <dt className="text-white/50 text-xs uppercase">Pathway(s)</dt>
            <dd className="font-semibold mt-0.5">{data.pathways}</dd>
          </div>
          <div>
            <dt className="text-white/50 text-xs uppercase">Readiness</dt>
            <dd className="font-bold text-gold-400 mt-0.5">{data.readinessScore}%</dd>
          </div>
          <div>
            <dt className="text-white/50 text-xs uppercase">Assets to build</dt>
            <dd className="font-semibold mt-0.5">{report.totalAssetsToBuild}</dd>
          </div>
        </dl>
      </div>

      <div className="px-8 py-6 bg-slate-50 border-b border-slate-200 text-xs text-slate-600 leading-relaxed">
        <Shield className="inline h-3.5 w-3.5 mr-1 text-navy-900" />
        Generated by {appConfig.appName} for counsel and consulting review only. Not legal advice.
        All claims require independent verification under applicable USCIS standards.
      </div>

      <div className="px-8 py-8 space-y-12">
        <section>
          <h3 className="text-xs font-bold uppercase tracking-widest text-gold-600 border-b border-slate-200 pb-2">
            Part I — Readiness benchmark report
          </h3>
          <div className="mt-6 dossier-report-embed">
            <BenchmarkReportView report={report} />
          </div>
        </section>

        <section className="border-t border-slate-200 pt-10">
          <h3 className="text-xs font-bold uppercase tracking-widest text-gold-600 border-b border-slate-200 pb-2">
            Part II — Profile Improvement Roadmap
          </h3>
          <p className="mt-4 text-sm text-slate-600">
            Quantified benchmark matrix and prioritized actions ({state.roadmap.length} items).
          </p>
          <div className="mt-6">
            <BenchmarkRoadmapPreviewTable rows={report.roadmapTable} />
          </div>
          <div className="mt-8">
            <QuantifiedRoadmapTable roadmaps={data.roadmaps} />
          </div>
        </section>
      </div>
    </article>
  )
}
